package ar.edu.unlu.juego;

public enum Eventos {

	CARTA_INEXISTENTE,
	CARTA_ESPECIAL_2,
	CARTA_ESPECIAL_4,
	CARTA_ESPECIAL_7,
	CARTA_ESPECIAL_10,
	CARTA_ESPECIAL_11,
	CARTA_ESPECIAL_12,
	CARTA_ESPECIAL_COMODIN, 
	CARTA_NO_COINCIDENTE, 
	CANTIDAD_JUGADORES,
	COMIENZA_EL_JUEGO,
	CAMBIAR_JUGADOR, 
	NO_ES_POSIBLE_ROBAR_CARTAS,
	CAMBIAR_RONDA, 
	CARTA_TIRADA_CORRECTAMENTE, 
	CARTA_TIRADA_NORMAL, 
	CAMBIO_COLOR,
	CARTAS,
	JUGADOR_INICIAL,
	CANTIDAD_JUGADORES_ERRONEA,
	ESPERANDO_JUGADORES,
	LISTOS_PARA_COMENZAR,
	MOSTRAR_OPCIONES,
	SELECCIONAR_OPCIONES,
	SELECCIONAR_CARTA_A_TIRAR, 
	TEST, CARTA_TIRADA,
	JODETE_LEVENTAS_MAL_CANTADO, 
	CANTO_JODETE, 
	JODETE_LEVENTAS_NO_CANTASTE, JODETE_LEVANTAS_0_CANTADO, JUEGO_TERMINADO, JUGADOR_ELIMINADO, NO_CANTO_JODETE_PRIMERO, BLOQUEAR_JUGADOR_ANTERIOR, TIPOS_DE_PALO, PRIMER_JUGADOR, MOSTRAR_PUNTOS
}

