package ar.edu.unlu.vista;

public enum EstadoJuego {
	MOSTRAR_OPCIONES_USUARIO,
	OPCION_SELECCIONADA,
	OPCION_B,
	OPCION_C,
	OPCION_D,
	OPCION_E,
	OPCION_F,
	OPCION_G,
	TIRANDO_CARTA,
	OPCION_INVALIDA,
	FIN,
	COMIENZO_JUEGO,
	CAMBIO_PALO, FIN_JUEGO
}
