package ar.edu.unlu.vista;

public enum Estados {
	CARGAR_NUMERO_JUGADORES,
	CARGAR_NOMBRE_JUGADORES,
	CARGANDO_NOMBRE_JUGADORES,
	JUEGO_CARGAR_NOMBRE_JUGADORES,
	COMIENZO_JUEGO,
	LISTOS_PARA_COMENZAR, FIN_JUEGO, JUEGO_OPCION_1_2, JUEGO_VER_RANKING,
}
