package ar.edu.unlu.juego;

public enum Eventos {

	CARTA_INEXISTENTE,
	CARTA_TIRADA,
	CARTA_ESPECIAL_2,
	CARTA_ESPECIAL_4,
	CARTA_ESPECIAL_7,
	CARTA_ESPECIAL_10,
	CARTA_ESPECIAL_11,
	CARTA_ESPECIAL_12,
	CARTA_ESPECIAL_COMODIN
}
