package ar.edu.unlu.juego;

public enum Eventos {

	CARTA_INEXISTENTE,
	CARTA_TIRADA,
	CARTA_ESPECIAL_2,
	CARTA_ESPECIAL_4,
	CARTA_ESPECIAL_7,
	CARTA_ESPECIAL_10,
	CARTA_ESPECIAL_11,
	CARTA_ESPECIAL_12,
	CARTA_ESPECIAL_COMODIN, 
	CARTA_NO_COINCIDENTE, 
	CANTIDAD_JUGADORES,
	COMIENZA_EL_JUEGO,
	CAMBIAR_JUGADOR, 
	NO_ES_POSIBLE_ROBAR_CARTAS,
	CAMBIAR_RONDA, 
	CARTA_TIRADA_CORRECTAMENTE, 
	CARTA_TIRADA_NORMAL,
}
